server:
  port: 80
spring:
  application:
    name: weixin-java-mp-web

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId: wxfba813b180e363f5
        secret: 25cd1c7ba6f6b084403b6a1f9deccd83
        token: linda2023
        aesKey: fhXUf1H4e8RWyr7BfXleGWd1LbpN0pYv4ufJ7ZTSWQy
